Github uses versions instead of tags, adjust report

diff --git a/.github/workflows/call_prune_container_registry.yaml b/.github/workflows/call_prune_container_registry.yaml
--- a/.github/workflows/call_prune_container_registry.yaml
+++ b/.github/workflows/call_prune_container_registry.yaml
@@ -12,17 +12,17 @@ name: Prune images from a container registry
         required: true
         type: string
       dry-run:
-        description: list which tags would be pruned
+        description: list which versions would be pruned
         default: false
         required: false
         type: boolean
       keep-latest:
-        description: never delete latest tag
+        description: never delete latest version
         default: true
         required: false
         type: boolean
       max-age:
-        description: prune images older that max age days
+        description: prune versions older that max age days
         required: true
         type: number
       repository:
@@ -78,7 +78,7 @@ jobs:
       run: |
         repository="$(basename "${REPO}")"
 
-        declare -a tags_array=()
+        declare -a versions_array=()
 
         next_url="${API_URL}/repositories/${USERNAME}/${repository}/tags/?page_size=${PAGE_SIZE}&page=1"
         while [[ -n ${next_url} ]]; do
@@ -95,14 +95,14 @@ jobs:
             if [[ -n ${tag_rows} ]]; then
                 while IFS=$'\t' read -r image_id tag last_updated; do
                     updated_epoch="$(date -ud "${last_updated}" +%s)"
-                    tags_array+=("${image_id}:${tag}:${updated_epoch}")
+                    versions_array+=("${image_id}:${tag}:${updated_epoch}")
                 done <<< "${tag_rows}"
             fi
 
             next_url="$(jq -r ".next // empty" <<< "${response}")"
         done
 
-        echo "TAGS=${tags_array[*]}" >> "${GITHUB_ENV}"
+        echo "VERSIONS=${versions_array[*]}" >> "${GITHUB_ENV}"
     - name: Collect tags using github api
       if: inputs.api-type == 'github'
       env:
@@ -117,7 +117,7 @@ jobs:
             echo "::warning::Pruning ${REPO}, but user ${USERNAME} is not the repository owner!"
         fi
 
-        declare -a tags_array=()
+        declare -a versions_array=()
 
         next_url="${API_URL}/users/${USERNAME}/packages/container/${repository}/versions?per_page=${PAGE_SIZE}&page=1"
         while [[ -n ${next_url} ]]; do
@@ -143,11 +143,9 @@ jobs:
                     .id as $id |
                     .updated_at as $updated_at |
                     (.metadata.container.tags // []) as $tags |
-                    if ($tags | length) == 0 then
-                        [$id, "[untagged]-\($id)", $updated_at] | @tsv
-                    else
-                        $tags[] | [$id, ., $updated_at] | @tsv
-                    end
+                    (if ($tags | length) == 0 then "[untagged]-\($id)" else $tags | join(",") end) as $merged_tags |
+                    [$id, $merged_tags, $updated_at] |
+                    @tsv
                 ' "${response_body}"
             )"; then
                 echo "::error::GitHub returned invalid or unexpected data"
@@ -157,7 +155,7 @@ jobs:
             if [[ -n ${tag_rows} ]]; then
                 while IFS=$'\t' read -r image_id tag last_updated; do
                     updated_epoch="$(date -ud "${last_updated}" +%s)"
-                    tags_array+=("${image_id}:${tag}:${updated_epoch}")
+                    versions_array+=("${image_id}:${tag}:${updated_epoch}")
                 done <<< "${tag_rows}"
             fi
 
@@ -172,37 +170,28 @@ jobs:
             fi
         done
 
-        echo "TAGS=${tags_array[*]}" >> "${GITHUB_ENV}"
+        echo "VERSIONS=${versions_array[*]}" >> "${GITHUB_ENV}"
     - name: Filter tags
       env:
         KEEP_LATEST: ${{ inputs.keep-latest }}
         MAX_AGE_DAYS: ${{ inputs.max-age }}
       run: |
-        IFS=" " read -ra tags_array <<< "${TAGS}"
-        latest_id=""
+        IFS=" " read -ra versions_array <<< "${VERSIONS}"
 
-        # filter based on age
         today="$(date +%F)"
         today_epoch="$(date -d "${today}" +%s)"
-        for i in $(seq 1 ${#tags_array[@]}); do
-            IFS=":" read -r id tag updated_epoch <<< "${tags_array[$((i - 1))]}"
+
+        for i in $(seq 1 ${#versions_array[@]}); do
+            IFS=":" read -r id tag updated_epoch <<< "${versions_array[$((i - 1))]}"
             age_days="$(((today_epoch - updated_epoch) / 86400))"
             status="keep"
             [[ ${tag} == "[untagged]-${id}" ]] && status="delete"
-            [[ ${tag} == "latest" ]] && latest_id="${id}"
             [[ ${age} -gt ${MAX_AGE_DAYS} ]] && status="delete"
-            tags_array["$((i - 1))"]="${id}:${tag}:${age_days}:${status}"
+            [[ ${KEEP_LATEST} == "true" ]] && [[ ",${tag}," == *,latest,* ]] && status="protected"
+            versions_array["$((i - 1))"]="${id}:${tag}:${age_days}:${status}"
         done
 
-        # protect latest
-        if [[ ${KEEP_LATEST} == "true" ]] && [[ -n ${latest_id} ]]; then
-            for i in $(seq 1 ${#tags_array[@]}); do
-                IFS=":" read -r id tag age _ <<< "${tags_array[$((i - 1))]}"
-                [[ ${id} == "${latest_id}" ]] && tags_array["$((i - 1))"]="${id}:${tag}:${age}:protected"
-            done
-        fi
-
-        echo "TAGS=${tags_array[*]}" >> "${GITHUB_ENV}"
+        echo "VERSIONS=${versions_array[*]}" >> "${GITHUB_ENV}"
     - name: Delete tags using docker api
       if: inputs.api-type == 'docker-v2' && ! inputs.dry-run
       env:
@@ -211,9 +200,9 @@ jobs:
         REPO: ${{ inputs.repository }}
       run: |
         repository="$(basename "${REPO}")"
-        IFS=" " read -ra tags_array <<< "${TAGS}"
-        for i in $(seq 1 ${#tags_array[@]}); do
-            IFS=":" read -r id tag age status <<< "${tags_array[$((i - 1))]}"
+        IFS=" " read -ra versions_array <<< "${VERSIONS}"
+        for i in $(seq 1 ${#versions_array[@]}); do
+            IFS=":" read -r id tag age status <<< "${versions_array[$((i - 1))]}"
             [[ ${status} != "delete" ]] && continue
             if ! http_code="$(
                 curl \
@@ -224,11 +213,11 @@ jobs:
                     --header "Authorization: Bearer ${JWT_TOKEN}" \
                     "${API_URL}/repositories/${USERNAME}/${repository}/tags/${id}/"
             )" || [[ ${http_code} -ne 204 ]]; then
-                tags_array["$((i - 1))"]="${id}:${tag}:${age}:delete_failed"
+                versions_array["$((i - 1))"]="${id}:${tag}:${age}:delete_failed"
                 echo "::warning::Failed to delete ${USERNAME}/${repository}:${id} (HTTP ${http_code})"
             fi
         done
-        echo "TAGS=${tags_array[*]}" >> "${GITHUB_ENV}"
+        echo "VERSIONS=${versions_array[*]}" >> "${GITHUB_ENV}"
     - name: Delete tags using github api
       if: inputs.api-type == 'github' && ! inputs.dry-run
       env:
@@ -238,13 +227,11 @@ jobs:
         TOKEN: ${{ secrets.token }}
       run: |
         repository="$(basename "${REPO}")"
-        declare -A deleted_versions
-        IFS=" " read -ra tags_array <<< "${TAGS}"
-        for i in $(seq 1 ${#tags_array[@]}); do
-            IFS=":" read -r id tag age status <<< "${tags_array[$((i - 1))]}"
+        IFS=" " read -ra versions_array <<< "${VERSIONS}"
+        for i in $(seq 1 ${#versions_array[@]}); do
+            IFS=":" read -r id tags age status <<< "${versions_array[$((i - 1))]}"
             [[ ${status} != "delete" ]] && continue
-            [[ -v deleted_versions["${id}"] ]] && continue
-            if http_code="$(
+            if ! http_code="$(
                 curl \
                     --silent \
                     --output /dev/null \
@@ -254,14 +241,27 @@ jobs:
                     --header "Accept: application/vnd.github+json" \
                     --header "X-GitHub-Api-Version: ${GITHUB_API_VERSION}" \
                     "${API_URL}/users/${USERNAME}/packages/container/${repository}/versions/${id}"
-            )" && [[ ${http_code} -eq 204 ]]; then
-                deleted_versions["${id}"]=1
-            else
-                tags_array["$((i - 1))"]="${id}:${tag}:${age}:delete_failed"
-                echo "::warning::Failed to delete ${USERNAME}/${repository}:${tag} (HTTP ${http_code})"
+            )" || [[ ${http_code} -ne 204 ]]; then
+                versions_array["$((i - 1))"]="${id}:${tags}:${age}:delete_failed"
+                echo "::warning::Failed to delete version ${id} (HTTP ${http_code})"
             fi
         done
-        echo "TAGS=${tags_array[*]}" >> "${GITHUB_ENV}"
+        echo "VERSIONS=${versions_array[*]}" >> "${GITHUB_ENV}"
+    - name: Reduce version tags
+      if: inputs.api-type == 'github'
+      run: |
+        IFS=" " read -ra versions_array <<< "${VERSIONS}"
+        for i in $(seq 1 ${#versions_array[@]}); do
+            IFS=":" read -r version tags age status <<< "${versions_array[$((i - 1))]}"
+            if [[ ${tags} == "[untagged]-${version}" ]]; then
+                num_tags=0
+            else
+                IFS=',' read -ra tags_array <<< "${tags}"
+                num_tags="${#tags_array[@]}"
+            fi
+            versions_array["$((i - 1))"]="${version}:${version}\\(${num_tags}\\tags):${age}:${status}"
+        done
+        echo "VERSIONS=${versions_array[*]}" >> "${GITHUB_ENV}"
     - name: Report
       env:
         DRY_RUN: ${{ inputs.dry-run }}
@@ -273,20 +273,20 @@ jobs:
         fi
 
         (
-            echo "Pruned images from ${REPO} that are older than ${MAX_AGE_DAYS} days."
+            echo "Pruned versions from ${REPO} that are older than ${MAX_AGE_DAYS} days."
             echo ""
-            echo "| Tag | Age (days) | Status |"
-            echo "|----:|-----------:|:------:|"
+            echo "| Version | Age (days) | Status |"
+            echo "|:--------|-----------:|:------:|"
         ) >> "${GITHUB_STEP_SUMMARY}"
 
-        IFS=" " read -ra tags_array <<< "${TAGS}"
-        if [[ ${#tags_array[@]} -eq 0 ]]; then
+        IFS=" " read -ra versions_array <<< "${VERSIONS}"
+        if [[ ${#versions_array[@]} -eq 0 ]]; then
             echo "| - | - | - |" >> "${GITHUB_STEP_SUMMARY}"
         fi
 
         deleted=0
-        for tag_info in "${tags_array[@]}" ; do
-            IFS=":" read -r _ tag age status <<< "${tag_info}"
+        for version_info in "${versions_array[@]}" ; do
+            IFS=":" read -r _ version age status <<< "${version_info}"
             case ${status} in
                 "protected") status="🔒" ;;
                 "keep") status="✔️" ;;
@@ -301,13 +301,13 @@ jobs:
                 "delete_failed") status="⚠️" ;;
                 *) status="❓" ;;
             esac
-            echo "| ${tag} | ${age} | ${status} |" >> "${GITHUB_STEP_SUMMARY}"
+            echo "| ${version//\\/ } | ${age} | ${status} |" >> "${GITHUB_STEP_SUMMARY}"
         done
 
         (echo ""; echo "(🔒 = Protected, ✔️ = Keep, 🚫 = Deleted, ⚠️ = Delete failed)"; echo "") >> "${GITHUB_STEP_SUMMARY}"
 
         if [[ ${DRY_RUN} == "true" ]]; then
-            echo "Dry-run: Would delete ${deleted} tags." >> "${GITHUB_STEP_SUMMARY}"
+            echo "Dry-run: Would delete ${deleted} versions." >> "${GITHUB_STEP_SUMMARY}"
         else
-            echo "Deleted ${deleted} tags." >> "${GITHUB_STEP_SUMMARY}"
+            echo "Deleted ${deleted} versions." >> "${GITHUB_STEP_SUMMARY}"
         fi
