Compare zwift screenshot to reference image

diff --git a/.github/workflows/zwift_visual_test.yaml b/.github/workflows/zwift_visual_test.yaml
--- a/.github/workflows/zwift_visual_test.yaml
+++ b/.github/workflows/zwift_visual_test.yaml
@@ -13,6 +13,8 @@ jobs:
     - name: Install dependencies
       run: sudo apt-get install -y x11-xserver-utils x11-apps
     - uses: netbrain/free-disk-space-action@v0.0.1
+    - name: Checkout
+      uses: actions/checkout@v7
     - name: Start Zwift and capture screenshot
       run: |
         export DISPLAY=":99"
@@ -30,8 +32,16 @@ jobs:
             -v /tmp/.X11-unix:/tmp/.X11-unix \
             netbrain/zwift:latest
         sleep 30
-        import -window root zwift-screenshot.png
+        magick import -window root zwift-screenshot.png
         docker kill zwift-visual-test
+    - name: Compare to reference screenshot
+      run: |
+        magick tests/zwift-visual-test/reference-screenshot.png -draw 'rectangle 175,430 625,455' zwift-screenshot-mask.png
+        different_pixels="$(magick compare -metric AE -read-mask zwift-screenshot-mask.png tests/zwift-visual-test/reference-screenshot.png zwift-screenshot.png zwift-screenshot-diff.png)"
+        if [[ ${different_pixels} != "0 (0)" ]]; then
+            echo "::error::Zwift screenshot differs from reference image!"
+            exit 1
+        fi
     - name: Upload screenshot
       uses: actions/upload-artifact@v7
       with:
